# String Tokenization

## Definition
Tokenization is the process of splitting a string of text into smaller units called tokens. Tokens can be words, subwords, characters, or sentences depending on the granularity required. It is the most fundamental step in converting raw text into a form that NLP models can process.

## Why It Is Needed
- **Unit of Analysis:** NLP models operate on tokens, not raw strings — tokenization defines the basic unit of processing.
- **Vocabulary Building:** Every unique token becomes an entry in the model's vocabulary, enabling numerical representation.
- **Boundary Detection:** Correctly splitting sentences and words ensures that meaning is preserved during downstream processing.

## Real-World Applications
- Splitting sentences into words for bag-of-words models
- Subword tokenization in transformer models like BERT and GPT
- Sentence tokenization for document summarization
- Character-level tokenization for spell correction systems
- Tweet tokenization handling hashtags, mentions, and emojis

## Important Points
- **Word Tokenization:** Splits text on whitespace and punctuation. e.g., `"I am happy"` → `["I", "am", "happy"]`.
- **Sentence Tokenization:** Splits a paragraph into individual sentences.
- **Subword Tokenization:** Handles unknown words by splitting into known subword units.
  - **BPE (Byte Pair Encoding):** Used in GPT models.
  - **WordPiece:** Used in BERT (`playing` → `play` + `##ing`).
  - **SentencePiece:** Language-agnostic tokenization used in multilingual models.
- **Character Tokenization:** Each character is a token — useful for morphologically rich languages.
- Whitespace-based tokenization is the simplest but fails on languages like Chinese and Japanese.

## Visual Understanding
```
[Insert diagram comparing Word Tokenization, Subword Tokenization (BPE/WordPiece),
 and Character Tokenization on the same input sentence]
```

## Implementation
Practical implementation will be added here.

## Key Takeaways
- Tokenization converts raw text into discrete units for model processing.
- The choice of tokenizer type (word, subword, char) affects vocabulary size and model performance.
- Subword tokenization balances vocabulary size and out-of-vocabulary handling.
- BERT uses WordPiece; GPT uses BPE — knowing this matters in interviews.
- Tokenization is language-dependent and must be chosen based on the target language.

In [1]:
import nltk

from nltk.tokenize import word_tokenize , sent_tokenize


text = "Hello world! NLP is amazing. Let's tokenize this sentence."

print("Word Tokens :",word_tokenize(text) )
print("length of Word Tokens :",len(word_tokenize(text)) )

print("sentence tokens :", sent_tokenize(text))
print("lengths of sentence tokens :", len(sent_tokenize(text)))

Word Tokens : ['Hello', 'world', '!', 'NLP', 'is', 'amazing', '.', 'Let', "'s", 'tokenize', 'this', 'sentence', '.']
length of Word Tokens : 13
sentence tokens : ['Hello world!', 'NLP is amazing.', "Let's tokenize this sentence."]
lengths of sentence tokens : 3


In [2]:
# using spacy

import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp(text)
print("Word Tokens:", [token.text for token in doc])
print("Sentence Tokens:", [sent.text for sent in doc.sents])

Word Tokens: ['Hello', 'world', '!', 'NLP', 'is', 'amazing', '.', 'Let', "'s", 'tokenize', 'this', 'sentence', '.']
Sentence Tokens: ['Hello world!', 'NLP is amazing.', "Let's tokenize this sentence."]


# NLP tasks

In [3]:
# basic word count and frequency disrtibution 

from collections import Counter

words = word_tokenize(text.lower())

word_freq = Counter(words)

print(len(words))
print(word_freq)

13
Counter({'.': 2, 'hello': 1, 'world': 1, '!': 1, 'nlp': 1, 'is': 1, 'amazing': 1, 'let': 1, "'s": 1, 'tokenize': 1, 'this': 1, 'sentence': 1})


In [4]:
# stopwords removal and frequency analysis

from nltk.corpus import stopwords
import contractions

stop_words = set(stopwords.words("english"))

# expanding contractions 
text = contractions.fix(text)
doc = nlp(text)
# removing punctuation 
words = [token.text for token in doc if not  token.is_punct]

# removing stop words
filtered_words = [word for word in words if word not in stop_words]

print(filtered_words)
print(len(filtered_words))
filtered_frequency = Counter(filtered_words)
print(filtered_frequency)

['Hello', 'world', 'NLP', 'amazing', 'Let', 'us', 'tokenize', 'sentence']
8
Counter({'Hello': 1, 'world': 1, 'NLP': 1, 'amazing': 1, 'Let': 1, 'us': 1, 'tokenize': 1, 'sentence': 1})


In [5]:
from nltk.corpus import stopwords
from collections import Counter
import contractions
import spacy

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Example text
text = "I can't believe this is happening! It isn't what I expected."

# Load stop words
stop_words = set(stopwords.words("english"))

# Expand contractions
text = contractions.fix(text)
print(text)
# Process text with spaCy
doc = nlp(text)

# Remove punctuation and convert to lowercase
words = [token.text.lower() for token in doc if not token.is_punct]

# Remove stop words
filtered_words = [word for word in words if word not in stop_words]

# Display results
print(filtered_words)
print("Number of words:", len(filtered_words))

# Count frequency
filtered_frequency = Counter(filtered_words)
print(filtered_frequency)

I cannot believe this is happening! It is not what I expected.
['believe', 'happening', 'expected']
Number of words: 3
Counter({'believe': 1, 'happening': 1, 'expected': 1})


*  NER with context analysis 

In [6]:
import spacy 
from collections import Counter

text = "Apple is looking at buying a uk startup for 1 billion USD"
doc=  nlp(text)


entity_freq  = Counter([ent.text for ent in doc.ents])

for ent , freq in entity_freq.most_common():
    print(f"entity : {ent} , Count: {freq}, Label : {nlp(ent)[0].ent_type_}")

entity : Apple , Count: 1, Label : ORG
entity : 1 billion USD , Count: 1, Label : MONEY


In [7]:
# N-grams with Frequency

from nltk.util  import ngrams

bigrams = list(ngrams(words , 2))
trigrams = list(ngrams(words, 3))

bigram_freq = Counter(bigrams)
trigram_freq = Counter(trigrams)


print(bigram_freq.most_common(5))
print(trigram_freq.most_common(5))

[(('i', 'can'), 1), (('can', 'not'), 1), (('not', 'believe'), 1), (('believe', 'this'), 1), (('this', 'is'), 1)]
[(('i', 'can', 'not'), 1), (('can', 'not', 'believe'), 1), (('not', 'believe', 'this'), 1), (('believe', 'this', 'is'), 1), (('this', 'is', 'happening'), 1)]


In [8]:
# keyword extractoon usinf tfidf with tokenization


from numpy import vectorize
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform([text])

feature_array = vectorizer.get_feature_names_out()

importance = X.toarray().flatten()
importance_words = sorted(zip(feature_array ,importance), key = lambda x : x[1], reverse = True)[:5]
print([word for word , _ in importance_words])

['apple', 'at', 'billion', 'buying', 'for']


In [9]:
for token in doc:
    print(f"Token: {token.text}, POS: {token.pos_}")

Token: Apple, POS: PROPN
Token: is, POS: AUX
Token: looking, POS: VERB
Token: at, POS: ADP
Token: buying, POS: VERB
Token: a, POS: DET
Token: uk, POS: PROPN
Token: startup, POS: VERB
Token: for, POS: ADP
Token: 1, POS: NUM
Token: billion, POS: NUM
Token: USD, POS: NOUN


# sentence similarity

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
sentences = ["I love NLP", "NLP is great for text processing", "Machine learning is amazing"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sentences)
print("Sentence Similarity Matrix:")
print((X * X.T).toarray())

Sentence Similarity Matrix:
[[2 1 0]
 [1 6 1]
 [0 1 4]]


# Text Summarization 

In [11]:
import spacy
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Input text
text = """Natural Language Processing (NLP) is a field of AI that enables machines to understand human language.
It is used in chatbots, sentiment analysis, and language translation.
One of the key challenges in NLP is understanding context and ambiguity in sentences.
Deep learning models like transformers have significantly improved NLP applications."""

# Process text with spaCy
doc = nlp(text)

# Tokenize words and compute frequency
words = [word.lower() for word in word_tokenize(text) if word.isalnum()]
filtered_freq = Counter(words)

# Compute sentence scores
sentence_scores = {}
for sent in doc.sents:
    for word in word_tokenize(sent.text.lower()):
        if word in filtered_freq:
            sentence_scores[sent.text] = sentence_scores.get(sent.text, 0) + filtered_freq[word]

# Sort sentences by score
sorted_sentences = sorted(sentence_scores, key=sentence_scores.get, reverse=True)

# Select top-ranked sentences for summary
summary = " ".join(sorted_sentences[:2])

# Print summary
print("Summary:", summary)

Summary: Natural Language Processing (NLP) is a field of AI that enables machines to understand human language.
 One of the key challenges in NLP is understanding context and ambiguity in sentences.

